### ISSUE TITLE
Support new engine

### ISSUE THREAD

**Issue by aviwad** [mattt/OpenAI#8]
the davinci 2 engine just launched. would be awesome if you could support it. thanks!

**Comment by scott-lydon** [comment]
I think you can simply pass the engine you would like to use as the argument to the "engine" parameter to the completion method.

**Comment by scott-lydon** [comment]
```swift
client.completions(engine: "davinci-codex", // <----------------here
                   prompt: prompt,
                   sampling: .temperature(0.0),
                   numberOfTokens: ...256,
                   numberOfCompletions: 1,
                   echo: false,
                   stop: ["//"],
                   presencePenalty: 0.0,
                   frequencyPenalty: 0.0,
                   bestOf: 1)
```

**Comment by mattt** [comment]
@aviwad As mentioned by @scott-lydon, additional engines can specified by string literal. I just opened https://github.com/mattt/OpenAI/pull/11, which documents the recommended pattern of creating a convenience API for engines used in your codebase.
